version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "increments/qiita-dev-group"

  - package-ecosystem: "github-actions"
    directory: "/actions/publish"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    reviewers:
      - "increments/qiita-dev-group"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "Asia/Tokyo"
    versioning-strategy: increase
    open-pull-requests-limit: 5
    reviewers:
      - "increments/qiita-dev-group"
