name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_test_execution_conditions:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: xt0rted/block-autosquash-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - check_test_execution_conditions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - run: yarn install
      - run: yarn run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        node:
          - "18.18.0"
          - "18.20.4"
          - "20.16.0"
    needs:
      - check_test_execution_conditions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn run test

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
      - check_test_execution_conditions
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.16.0"
      - run: yarn install
      - run: yarn run build
        env:
          NODE_ENV: "production"
